# DO NOT CHANGE THIS
config-version: 2

ingots:
  copper:
    name: "&cCopper Repair Ingot"
    lore:
      - ""
      - This ingot adds 50 durability to your item.
    durability: 50
    percentage: false
    item: COPPER_INGOT
    sound: BLOCK_ANVIL_USE
  iron:
    name: "&aIron Repair Ingot"
    lore:
      - ""
      - This ingot adds 50% of your item's max durability to your item.
    durability: 50
    percentage: true
    item: IRON_INGOT
    sound: BLOCK_ANVIL_USE
